version: '3.7'

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    container_name: champs-api